name = "atxrr"
pages_build_output_dir = "dist"
compatibility_date = "2025-12-01"
compatibility_flags = ["nodejs_compat"]
upload_source_maps = true

[placement]
mode = "smart"

[vars]
PUBLIC_DIRECTUS_URL = "https://directus.atxrubberroundup.com/"

[env.production.vars]
PUBLIC_DIRECTUS_URL = "https://directus.atxrubberroundup.com/"
SITE_URL = "https://atxrubberroundup.com"

[[env.production.kv_namespaces]]
id = "93531e2f397b4411b1c673e240ca7ffd"
binding = "CACHE"
